/* Teks baku laporan: Pendahuluan (teori), Maksud & Tujuan, Ruang Lingkup, Penutup, Daftar Pustaka.
   Format blok: {h: judul sub-bagian (opsional)}, {p: paragraf}, {b: [butir-butir]} */
var LAP_TEKS = {
  umum: [
    { p: 'Pertumbuhan merupakan salah satu indikator terbaik untuk menilai status gizi anak di bawah lima tahun (balita). Masa balita, terutama 1.000 Hari Pertama Kehidupan (HPK), adalah periode pertumbuhan dan perkembangan yang sangat pesat sehingga gangguan gizi pada masa ini berdampak jangka pendek maupun jangka panjang, antara lain meningkatnya risiko kesakitan dan kematian, terhambatnya perkembangan kognitif, rendahnya produktivitas pada usia dewasa, serta meningkatnya risiko penyakit tidak menular (Black dkk., 2013; Victora dkk., 2021).' },
    { p: 'Penilaian status gizi balita di Indonesia menggunakan Standar Antropometri Anak sebagaimana diatur dalam Peraturan Menteri Kesehatan Nomor 2 Tahun 2020, yang mengacu pada WHO Child Growth Standards. Status gizi ditentukan berdasarkan nilai ambang batas z-skor (simpang baku) dari tiga indeks utama, yaitu berat badan menurut umur (BB/U), panjang atau tinggi badan menurut umur (PB/U atau TB/U), dan berat badan menurut panjang atau tinggi badan (BB/PB atau BB/TB) (Kemenkes RI, 2020; WHO, 2006).' },
    { p: 'Hasil Survei Status Gizi Indonesia (SSGI) tahun 2024 menunjukkan prevalensi stunting pada balita secara nasional sebesar 19,8%, menurun dari 21,5% pada tahun 2023. Prevalensi wasting (gizi kurang dan gizi buruk) sebesar 7,4% dan overweight (gizi lebih) sebesar 3,4%. Meskipun terus menurun, angka tersebut menunjukkan bahwa Indonesia masih menghadapi beban ganda masalah gizi, yaitu kekurangan gizi dan kelebihan gizi yang terjadi secara bersamaan, sehingga upaya pemantauan pertumbuhan dan intervensi gizi di tingkat masyarakat tetap perlu diperkuat (BKPK Kemenkes RI, 2025; Presiden RI, 2021).' },
    { p: 'Masalah gizi yang sering ditemukan pada balita di Indonesia adalah sebagai berikut.' },
    { h: 'a.', t: 'Stunting (Pendek dan Sangat Pendek)' },
    { p: 'Stunting adalah kondisi gagal tumbuh pada balita akibat kekurangan gizi kronis dan infeksi berulang, terutama pada periode 1.000 HPK, yang ditandai dengan panjang atau tinggi badan yang berada di bawah standar. Berdasarkan indeks PB/U atau TB/U, anak dikategorikan pendek (stunted) apabila z-skor berada antara −3 SD sampai kurang dari −2 SD, dan sangat pendek (severely stunted) apabila z-skor kurang dari −3 SD (Kemenkes RI, 2020; Presiden RI, 2021).', lv: 3 },
    { p: 'Kerangka konseptual gizi ibu dan anak (UNICEF, 2020) menjelaskan bahwa stunting disebabkan oleh faktor langsung, yaitu asupan makanan yang tidak memadai dan penyakit infeksi, serta faktor tidak langsung, yaitu ketersediaan pangan di rumah tangga, praktik pengasuhan dan pemberian makan, akses air bersih dan sanitasi, serta akses terhadap pelayanan kesehatan. Faktor yang banyak berperan antara lain:', lv: 3 },
    { b: ['Praktik pemberian makan yang tidak tepat, termasuk tidak diberikannya ASI eksklusif serta MP-ASI yang terlambat, kurang beragam, atau kurang mengandung protein hewani (WHO, 2023a).', 'Penyakit infeksi berulang seperti diare, ISPA, dan kecacingan yang berkaitan dengan sanitasi dan higiene yang kurang baik.', 'Kekurangan gizi pada ibu sebelum dan selama kehamilan, misalnya Kurang Energi Kronis (KEK), yang meningkatkan risiko bayi lahir dengan berat atau panjang badan rendah.', 'Imunisasi dasar yang tidak lengkap dan paparan asap rokok di lingkungan rumah.'], lv: 3 },
    { h: 'b.', t: 'Berat Badan Kurang (Underweight) serta Gizi Kurang dan Gizi Buruk (Wasting)' },
    { p: 'Berat badan kurang (underweight) ditentukan dengan indeks BB/U, yaitu berat badan kurang apabila z-skor −3 SD sampai kurang dari −2 SD dan berat badan sangat kurang apabila z-skor kurang dari −3 SD. Indeks ini menggambarkan masalah gizi secara umum, baik yang bersifat akut maupun kronis (Kemenkes RI, 2020).', lv: 3 },
    { p: 'Wasting ditentukan dengan indeks BB/PB atau BB/TB, yaitu gizi kurang apabila z-skor −3 SD sampai kurang dari −2 SD dan gizi buruk apabila z-skor kurang dari −3 SD. Wasting mencerminkan kekurangan gizi akut akibat asupan yang tidak mencukupi dan/atau penyakit infeksi, serta berhubungan erat dengan peningkatan risiko kematian pada balita. Oleh karena itu, balita dengan wasting perlu segera ditemukan, dipantau, dan ditatalaksana sesuai pedoman, termasuk pemberian makanan tambahan pemulihan, konseling pemberian makan, dan rujukan apabila disertai komplikasi medis (WHO, 2023b; Kemenkes RI, 2019).', lv: 3 },
    { h: 'c.', t: 'Gizi Lebih dan Obesitas' },
    { p: 'Berdasarkan indeks BB/PB atau BB/TB, balita dikategorikan berisiko gizi lebih apabila z-skor lebih dari +1 SD sampai +2 SD, gizi lebih apabila lebih dari +2 SD sampai +3 SD, dan obesitas apabila lebih dari +3 SD (Kemenkes RI, 2020). Gizi lebih pada balita terutama dipengaruhi oleh konsumsi makanan dan minuman tinggi energi, gula, dan lemak, seperti jajanan kemasan dan minuman manis, kurangnya aktivitas fisik, serta lamanya waktu menatap layar. Obesitas pada masa anak cenderung berlanjut hingga dewasa dan meningkatkan risiko penyakit tidak menular (WHO, 2016).', lv: 3 },
    { h: '', t: 'Upaya Pencegahan dan Penanggulangan' },
    { p: 'Pencegahan dan penanggulangan masalah gizi pada balita dilakukan melalui intervensi spesifik dan sensitif, antara lain pemantauan pertumbuhan secara rutin di posyandu, promosi ASI eksklusif dan MP-ASI yang tepat, edukasi gizi seimbang dengan panduan Isi Piringku, pemberian makanan tambahan berbahan pangan lokal, peningkatan cakupan imunisasi, serta perbaikan air bersih, sanitasi, dan perilaku hidup bersih dan sehat (Kemenkes RI, 2014; Presiden RI, 2021). Kunjungan lapangan atau kunjungan rumah oleh tenaga kesehatan merupakan salah satu bentuk pemantauan dan pendampingan langsung kepada keluarga balita untuk mengidentifikasi masalah gizi beserta faktor penyebabnya, memberikan edukasi dan konseling yang sesuai dengan kondisi masing-masing keluarga, serta menindaklanjuti kasus yang memerlukan penanganan lebih lanjut.', lv: 2 }
  ],
  maksud: 'Kegiatan kunjungan lapangan balita dimaksudkan untuk memantau pertumbuhan dan status gizi balita secara langsung di tingkat keluarga. Tujuan kegiatan ini adalah (1) mengidentifikasi balita dengan masalah gizi (underweight, stunting, wasting, dan gizi lebih) beserta faktor-faktor yang memengaruhinya; (2) memberikan edukasi dan konseling gizi untuk meningkatkan pengetahuan, sikap, dan perilaku orang tua/wali dalam mewujudkan tumbuh kembang balita yang optimal; serta (3) memantau perkembangan status gizi balita dari waktu ke waktu sebagai dasar tindak lanjut program gizi.',
  ruang: 'Ruang lingkup kegiatan ini adalah balita yang menjadi sasaran kunjungan lapangan di posyandu wilayah kerja Puskesmas Moncongloe Kabupaten Maros, meliputi pengukuran antropometri (berat badan, panjang/tinggi badan, lingkar kepala, dan lingkar lengan atas), penilaian status gizi, pengkajian pemberian ASI dan MP-ASI, kebiasaan makan, serta faktor determinan, disertai pemberian edukasi gizi kepada orang tua/wali balita.',
  penutup: 'Demikian laporan kegiatan kunjungan lapangan balita ini disusun sebagai bahan evaluasi dan dasar tindak lanjut program gizi di Puskesmas Moncongloe. Perbaikan mutu pelayanan kesehatan primer sebagai garda terdepan serta penanggulangan masalah gizi balita memerlukan upaya promotif, preventif, kuratif, dan rehabilitatif yang dilaksanakan secara terpadu dengan dukungan lintas program dan lintas sektor.',
  pustaka: [
    'Badan Kebijakan Pembangunan Kesehatan Kementerian Kesehatan RI. (2025). Survei Status Gizi Indonesia (SSGI) 2024 dalam angka. Jakarta: Kementerian Kesehatan RI.',
    'Black, R. E., Victora, C. G., Walker, S. P., Bhutta, Z. A., Christian, P., de Onis, M., dkk. (2013). Maternal and child undernutrition and overweight in low-income and middle-income countries. The Lancet, 382(9890), 427–451.',
    'Kementerian Kesehatan RI. (2014). Peraturan Menteri Kesehatan Nomor 41 Tahun 2014 tentang Pedoman Gizi Seimbang. Jakarta: Kementerian Kesehatan RI.',
    'Kementerian Kesehatan RI. (2019). Peraturan Menteri Kesehatan Nomor 29 Tahun 2019 tentang Penanggulangan Masalah Gizi bagi Anak Akibat Penyakit. Jakarta: Kementerian Kesehatan RI.',
    'Kementerian Kesehatan RI. (2020). Peraturan Menteri Kesehatan Nomor 2 Tahun 2020 tentang Standar Antropometri Anak. Jakarta: Kementerian Kesehatan RI.',
    'Presiden Republik Indonesia. (2021). Peraturan Presiden Nomor 72 Tahun 2021 tentang Percepatan Penurunan Stunting. Jakarta: Sekretariat Negara.',
    'UNICEF. (2020). UNICEF conceptual framework on maternal and child nutrition. New York: United Nations Children’s Fund.',
    'Victora, C. G., Christian, P., Vidaletti, L. P., Gatica-Domínguez, G., Menon, P., & Black, R. E. (2021). Revisiting maternal and child undernutrition in low-income and middle-income countries: variable progress towards an unfinished agenda. The Lancet, 397(10282), 1388–1399.',
    'World Health Organization. (2006). WHO child growth standards: length/height-for-age, weight-for-age, weight-for-length, weight-for-height and body mass index-for-age: methods and development. Geneva: WHO.',
    'World Health Organization. (2016). Report of the Commission on Ending Childhood Obesity. Geneva: WHO.',
    'World Health Organization. (2023a). WHO guideline for complementary feeding of infants and young children 6–23 months of age. Geneva: WHO.',
    'World Health Organization. (2023b). WHO guideline on the prevention and management of wasting and nutritional oedema (acute malnutrition) in infants and children under 5 years. Geneva: WHO.'
  ]
};
